```{r}
library(tidyverse)
library(fs)
```

```{r}
dir_tree("..")
```

```{r}
# "../src/utils.py"
df <- read_csv("../data/daily.csv")
```

```{r}
p1 <-
    df %>%
    filter(lubridate::month(updateDate) >= 2) %>%
    filter(provinceName %>% str_detect('上海')) %>%
    group_by(updateDate) %>%
    summarise(confirmed = sum(confirmed)) %>%
    ungroup() %>%
    arrange(updateDate) %>%
    mutate(growth_rate = log(confirmed),
           growth_rate = c(NA, diff(growth_rate))) %>%
    ggplot() +
    aes(x = updateDate, y = growth_rate) +
    geom_smooth(color = add2ggplot::red_one, linetype = 3) +
    geom_line(color = add2ggplot::red_one) +
    add2ggplot::theme_grey_and_red()
```

```{r}
p1 +
    geom_text(aes(label = scales::percent(growth_rate)), color = add2ggplot::white_one) +
    labs(y = '增长率', x = '更新日期', caption = '备注: 虚线为拟合线',
         title = '数据有点异常，9号以后跌的太厉害，本身是返工潮'
         ) +
    scale_x_date(date_breaks = "1 day", date_labels = "%m-%d(周%w)") +
    theme(
        axis.text.x = element_text(angle = 90)
    ) +
ggsave("../output/")
```

